---
version: '2'
services:
  shrink:
    image: equivalent/shrink:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "DEFAULTS=true"
    volumes:
      - /tmp/shrink:/tmp/shrink
      - /tmp/shrink_processed:/tmp/shrink_processed
